### ISSUE TITLE
link issue from  https://github.com/astaxie/build-web-application-with-golang/issues/578

### ISSUE THREAD

**Issue by wheelcomplex** [wheelcomplex/wander#1]
here is the code and summary for the test.

https://github.com/wheelcomplex/wander/tree/master/go-vs-php-file-parse

**Comment by liaosiwei** [comment]
首先尝试了作者的程序，性能如下：

<pre><code>
go-file-parser 2015/12/28 13:11:52 Go, parsed file 100m.lines.testdata.txt in 1m17.869963699s, 100000000 lines, 4768 MB, 61 MB/s.
</code></pre>

我试了下几个程序，对比了下(使用的作者提供的readme中的命令生成的测试文件)：

第一个程序用最常见的方法

<pre><code>
1   package main
2
3   import (
4       "time"
5       "os"
6       "fmt"
7       "bufio"
8       "strconv"
9       "log"
10      "bytes"
11  )
12
13  var totalSize float64
14
15  func trace(msg string) func(){
16      start := time.Now()
17      log.Printf("enter %s", msg)
18      return func() {
19          elapse := time.Since(start)
20          log.Printf("exit %s (%s) %.2fMB/s", msg, elapse, totalSize / elapse.Seconds())
21      }
22  }
23
24
25  func main() {
26      defer trace("file parser using golang")()
27      if len(os.Args) != 2 {
28          panic("illegal parameters")
29      }
30      f, err := os.Open(os.Args[1])
31      if err != nil {
32          panic(fmt.Sprintf("open file failed, %s", err))
33      }
34      defer f.Close()
35      input := bufio.NewScanner(f)
36      for input.Scan() {
37          tokens := bytes.Fields(input.Bytes())
38          totalSize += float64(len(input.Bytes()))
39          if len(tokens) < 9 {
40              continue
41          }
42          strconv.ParseInt(string(tokens[8]), 10, 0)
43      }
44      totalSize = totalSize / (1 << 20)
45  }
</code></pre>

结果如下：

<pre><code>
2015/12/28 14:18:18 enter file parser using golang
2015/12/28 14:02:22 exit file parser using golang (4m23.291867019s) 17.75MB/s
</code></pre>

结果差很多，于是尝试改成ReadBytes，如下：

<pre><code>
26  func main() {
27      defer trace("file parser using golang")()
28      if len(os.Args) != 2 {
29          panic("illegal parameters")
30      }
31      f, err := os.Open(os.Args[1])
32      if err != nil {
33          panic(fmt.Sprintf("open file failed, %s", err))
34      }
35      defer f.Close()
36      input := bufio.NewReaderSize(f, 1 << 16)
37      for {
38          line, err := input.ReadBytes('\n');
39          if err != nil {
40              if err == io.EOF {
41                  totalSize = totalSize / (1 << 20)
42                  return
43              } else {
44                  panic(err)
45              }
46          }
47          totalSize += float64(len(line))
48          tokens := bytes.Fields(line)
49          if len(tokens) < 9 {
50              continue
51          }
52          strconv.ParseInt(string(tokens[8]), 10, 0)
53      }
54  }
</code></pre>

结果如下：

<pre><code>
2015/12/28 14:18:18 enter file parser using golang
2015/12/28 14:22:04 exit file parser using golang (3m46.389715288s) 21.06MB/s
</code></pre>

进步不大，再次更改，把bytes.Field替换成bytes.SplitN：

<pre><code>
26  func main() {
27      defer trace("file parser using golang")()
28      if len(os.Args) != 2 {
29          panic("illegal parameters")
30      }
31      f, err := os.Open(os.Args[1])
32      if err != nil {
33          panic(fmt.Sprintf("open file failed, %s", err))
34      }
35      defer f.Close()
36      input := bufio.NewReaderSize(f, 1 << 16)
37      for {
38          line, err := input.ReadBytes('\n');
39          if err != nil {
40              if err == io.EOF {
41                  totalSize = totalSize / (1 << 20)
42                  return
43              } else {
44                  panic(err)
45              }
46          }
47          totalSize += float64(len(line))
48          tokens := bytes.SplitN(line, []byte(" "), 10)
49          if len(tokens) < 9 {
50              continue
51          }
52          strconv.ParseInt(string(tokens[8]), 10, 0)
53      }
54  }
</code></pre>

结果提升很多：

<pre><code>
2015/12/28 14:38:26 enter file parser using golang
2015/12/28 14:39:58 exit file parser using golang (1m31.92266206s) 51.87MB/s
</code></pre>

尝试把ReadBytes改成ReadSlice，结果还能提升：

<pre><code>
2015/12/28 14:41:35 enter file parser using golang
2015/12/28 14:42:45 exit file parser using golang (1m9.387812318s) 68.72MB/s
</code></pre>

结果跟作者的几乎一致。
然后再尝试把bufio.NewReaderSize(f, 1 << 16)改为bufio.NewReader(f)，使用默认大小的缓冲区，结果如下：

<pre><code>
2015/12/28 14:58:33 enter file parser using golang
2015/12/28 14:59:42 exit file parser using golang (1m9.062535217s) 69.04MB/s
</code></pre>

可见，缓冲区大小默认值就很好，根据上面的结果，可见瓶颈主要是bytes.Field函数了，用bytes.SplitN来替换节省了后面一部分的字符串分割的计算，所以再回到第一个方法，这次用bytes.SplitN:

<pre><code>
25  func main() {
26      defer trace("file parser using golang")()
27      if len(os.Args) != 2 {
28          panic("illegal parameters")
29      }
30      f, err := os.Open(os.Args[1])
31      if err != nil {
32          panic(fmt.Sprintf("open file failed, %s", err))
33      }
34      defer f.Close()
35      input := bufio.NewScanner(f)
36      for input.Scan() {
37          tokens := bytes.SplitN(input.Bytes(), []byte(" "), 10)
38          totalSize += float64(len(input.Bytes()))
39          if len(tokens) < 9 {
40              continue
41          }
42          strconv.ParseInt(string(tokens[8]), 10, 0)
43      }
44      totalSize = totalSize / (1 << 20)
45  }
</code></pre>

结果如下：

<pre><code>
2015/12/28 15:02:41 enter file parser using golang
2015/12/28 15:03:52 exit file parser using golang (1m11.236572381s) 65.60MB/s
</code></pre>

因此，golang提供的文件操作接口是没问题的，关键是看自己的实现了，这里为了找到一个字段的值采用了Field和SplitN的方法，这些方法可能还不是最优的，自己写一个性能应该会更好。

**Comment by wheelcomplex** [comment]
@liaosiwei Thanks for your test, would you please to run the parser.php with php 7.0 in the same machine? I think we need the speed of php 7.0 parser for reference.

**Comment by liaosiwei** [comment]
没有条件测试php7的性能，有个php5的。。。
<pre><code>
php, parsed file 100m.lines.testdata.txt in 391.818, 100000001 lines, 4673 MB, speed 11 MB/s
</pre></code>

**Comment by lixuancn** [comment]
php7的交给我了。稍等

**Comment by lixuancn** [comment]
1、Go1.5.1
➜  go-vs-php-file-parse git:(master) ✗ ./parser -f 100m.lines.testdata.txt
go-file-parser 2015/12/28 16:18:14 Go, parsing 100m.lines.testdata.txt(4768 MB), read buffer size 65535 ...
go-file-parser 2015/12/28 16:19:05 read done, 100000000 lines, 5000000000 bytes, parse size 486436015838
go-file-parser 2015/12/28 16:19:05 Go, parsed file 100m.lines.testdata.txt in 51.186681988s, 100000000 lines, 4768 MB, 93 MB/s.

2、php5.5.29
➜  go-vs-php-file-parse git:(master) ✗ php parser.php -f 100m.lines.testdata.txt
php 7.0, parsing file 100m.lines.testdata.txt(4768 MB) ...

php, parsed file 100m.lines.testdata.txt in 836.214, 100000001 lines, 4673 MB, speed 5 MB/s

3、php7.0
➜  go-vs-php-file-parse git:(master) ✗ php parser.php -f 100m.lines.testdata.txt
php 7.0, parsing file 100m.lines.testdata.txt(4768 MB) ...
php, parsed file 100m.lines.testdata.txt in 717.051, 100000001 lines, 4673 MB, speed 6 MB/s

这个结果...这PHP也太慢了。。。

**Comment by wheelcomplex** [comment]
@lixuancn I know nothing about php profiling, would you please to profiling/optimize the parser.php and let me know what happen to the parser.php?

**Comment by lixuancn** [comment]
如果我用之前的文件（13G）的，不是你生产的这个。
PHP5.6：158.86秒
PHP7：44.451秒
Go：56秒左右

GO我的测试：
    上面的各种方法，无论是bufio.NewReaderSize(f, 1 << 16)或者bufio.NewReader(f) ，无论是ReadBytes或者ReadSlice。结果都是350秒左右。

当使用bytes.SplitN这个后，立马从350秒到56秒！不过不可否认，PHP7的性能的确太强悍了

**Comment by lixuancn** [comment]
如果我用之前的文件（13G）的，不是你生产的这个。
PHP5.6：158.86秒
PHP7：44.451秒
Go：56秒左右

GO我的测试：
    上面的各种方法，无论是bufio.NewReaderSize(f, 1 << 16)或者bufio.NewReader(f) ，无论是ReadBytes或者ReadSlice。结果都是350秒左右。

当使用bytes.SplitN这个后，立马从350秒到56秒！不过不可否认，PHP7的性能的确太强悍了

**Comment by liaosiwei** [comment]
把你最终的程序贴出来撒，go和php的

**Comment by wheelcomplex** [comment]
@lixuancn Please provide all files need for your test, include 13GB log file(you should replace private information and gzip it) and php parser code + Go parser code, http://pan.baidu.com/ would be a place to share your files. Just talking about your result is not a proper way for discussion.

**Comment by lixuancn** [comment]
http://yunpan.cn/curPcRmArVGMA （提取码：6822）

下载解压后请看README。

只有1.8M

**Comment by liaosiwei** [comment]
你的go程序和php程序逻辑是不一样的，把你的go改的跟php的逻辑一样就会发现go比php要快了。

**Comment by wheelcomplex** [comment]
@liaosiwei yes, exactly, I have modify the go parser from lixuancn to match php parser logic, here is it https://github.com/wheelcomplex/wander/commit/ad21abd1316278685f51bbad5859710470dfd626 and looks like a litte faster then php.
@lixuancn Thanks for the test code. We are improved by this test case.

**Comment by wheelcomplex** [comment]
Hi all,
Just let you know ,after https://github.com/wheelcomplex/wander/commit/845e7d6f38e43601446199096e915b7ba85c3c77 Go parser got 3x speed boost, LOL.
